name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}  # Your EC2 Public IP
        username: ec2-user  # Change to ubuntu if using Ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

    - name: Pull Latest Code and Restart Container
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ec2-user/app  # Change this to your project directory
        git pull origin main
        docker stop myapp || true
        docker rm myapp || true
        docker build -t myapp .
        docker run -d -p 5000:5000 --name myapp myapp
        EOF
